version: "3.1"

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
        PG_PASSWORD: root
    restart: always
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
       - "5432:5432"
    networks:
      - botnet

    env_file:
          - '.env'





  tgbot:
    container_name: horo
    build:
      context: .

    command: python horo.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    depends_on:
      - db

networks:
  botnet:
    driver: bridge
#volumes:
#  pgdata: { }
