version: "3.1"

services:
  tgbot:
    container_name: horo
    build:
      context: .

    command: python horo.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
networks:
  botnet:
    driver: bridge
